use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(tag = "code", content = "params", rename_all = "camelCase")]
pub enum AppMessage {
    AuthStorage,
    AuthCancelled,
    AuthNetwork,
    AuthLoginFailed,
    FloodWait,
    FloodWaitSeconds { seconds: u64 },
    InvalidPhone,
    CodeExpired,
    InvalidCode,
    IncorrectPassword,
    TelegramRejected { name: String },
    EmailSetupRequired,
    AdditionalLoginStep,
    MissingCode,
    SignUpRequired,
    PasswordVerificationFailed,
    LoginIncomplete,
    InternationalPhoneRequired,
    SignOutInProgress,
    RequestCodeFirst,
    RestartLogin,
    OpenLinkFailed,
    MissingCredentials,
    InvalidApiId,
    MissingDataCenter,
    QrMigrationFailed,
    QrLoginIncomplete,
    InvalidPhrase,
    InvalidPrice,
    ProductNotFound,
    WatchStorage,
    WatchStorageOpen,
    ChatStorage,
    InvalidChatSelection,
    ChatListIncomplete,
    ChatLoadFailed,
    ChatRateLimit,
    ChatRateLimitSeconds { seconds: u64 },
    SearchStorage,
    SearchFailed,
    SearchBusy,
    SearchNeedsProducts,
    SearchNeedsChats,
    InvalidSearchCutoff,
    DeliveryApp,
    DeliverySms,
    DeliveryCall,
    DeliveryEmail { email: String },
    DeliveryFragment { url: String },
    DeliveryMissedCall { prefix: String },
    DeliveryFlashCall,
    DeliverySmsPhrase,
}

#[cfg(test)]
#[path = "app_message/tests.rs"]
mod tests;
